language: go

go:
  - "1.10.x"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -q
  - sudo apt-get -y install docker-compose
  - sudo docker pull gitlab/gitlab-ce

script:
  - go test -v ./...
